apiVersion: apps/v1
kind: Deployment
metadata:
    name: mydeploy
spec:
  replicas: 3
  strategy:
    type: rollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  selector:
     matchLabels:
       image: tomcat
  template:
    metadata:
      name: podd
      labels:
        image: tomcat
    spec:
      containers:
      - name: c1
        image: imblessingdavid/tomcat:$BUILD_NUMBER  

---

apiVersion: v1 
kind: service 
metadata: 
  name: mysvc 
spec:
  selector: 
     image: tomcat 
  type: NodePort
  ports: 
  - port: 8080
    targetPort: 8080
